name: Repo count badge (incl. private)

on:
  workflow_dispatch:
  schedule:
    - cron: "21 6 * * *"  # runs daily at 06:21 UTC

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get totals from GitHub API
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -euo pipefail
          DATA=$(curl -fsSL -H "Authorization: Bearer $GH_TOKEN" https://api.github.com/user)
          PUBLIC=$(echo "$DATA"  | jq -r .public_repos)
          PRIVATE=$(echo "$DATA" | jq -r .total_private_repos)
          TOTAL=$((PUBLIC + PRIVATE))

          mkdir -p out
          cat > out/repos_total.json <<JSON
          { "schemaVersion": 1, "label": "repos", "message": "$TOTAL", "color": "informational" }
          JSON

      - name: Upload repos_total.json
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: out/repos_total.json
